### ISSUE TITLE
F*** local sign ups through NodeJS

### ISSUE THREAD

**Issue by ynigoreyes** [TTUSDC/ttuacm-website#150]
we can remove almost half the code in the server if we were to completely buy into Firebase. 

It is actually possible to import all of our existing users to Firebase. We then do not need to handle ANY authentication or email sends or password resets or OAuth. We can have EVERYTHING handled by Firebase Authentication. 

I would like to implement this because "No Code is the Best Code"

**Comment by madewithsmiles** [comment]
Sweet! Let's do this!
