### ISSUE TITLE
Make the footer look a little cleaner on mobile

### ISSUE THREAD

**Issue by ynigoreyes** [TTUSDC/ttuacm-website#190]
Josh says no so lol

**Comment by ynigoreyes** [comment]
So I tried this, and it looks bad without the links and About lol. However, I think maybe splitting up the list of links in mobile view into columns would make it look a little nicer.

Not sure how you set up the footer. So i think @madewithsmiles would have a better shot at fixing this...

**Comment by ynigoreyes** [comment]
I have been asking around and they say that we should remove the links and about section on mobile

**Comment by madewithsmiles** [comment]
Sounds good, I will try that then. My idea was to use collapsible. Let me
know what you think

**Comment by ynigoreyes** [comment]
Mmmmmm nah i don't think collapsible is the way to go. I just don't think those sections are really needed all together.
