### ISSUE TITLE
Fix the mobile/desktop view of both the app bar

### ISSUE THREAD

**Issue by madewithsmiles** [TTUSDC/ttuacm-website#86]
We would like to make it so it looks like how GitHub appears in mobile view

**Comment by ynigoreyes** [comment]
The navbar also changes sizes when we click links, as you stated in #151

**Comment by ynigoreyes** [comment]
![Preview](https://user-images.githubusercontent.com/26727346/54927234-c3227680-4edf-11e9-9e8a-97abd63c70f7.jpg)

Is this what we are going for?

**Comment by ynigoreyes** [comment]
![Screenshot_20190325-092536_Chrome](https://user-images.githubusercontent.com/26727346/54927421-23b1b380-4ee0-11e9-9342-6c6314064bbd.jpg)

Material UI also has tabs that we can use

**Comment by ynigoreyes** [comment]
Fixed the Footer!
